/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildHealth;

import Business.ChildHealth.ChildMentalHealthAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemUser.SystemUserWorkAreaJPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class ChildMentalHealthRequestForm extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private ChildMentalHealthAttributes childMentalHealthAttributes;

    /**
     * Creates new form ChildMentalHealthRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param organization
     * @param enterprise
     * @param user
     */
    public ChildMentalHealthRequestForm(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        this.childMentalHealthAttributes = new ChildMentalHealthAttributes();
        Date date = new Date();
        jDateChooser1.setMaxSelectableDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtChildLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtChildFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDiseasePeriod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFullNameParent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMobileNumberParent = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtChildInsuranceNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredMentalHealthCareLocation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtChildPhysicianName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtChildPhysicianLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioButtonYes = new javax.swing.JRadioButton();
        radioButtonNo = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMentalHealthDiagnosisType = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Child Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 192, -1, -1));
        add(txtChildLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 186, 132, -1));

        jLabel2.setText("Child Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 155, -1, -1));
        add(txtChildFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 149, 132, -1));

        jLabel3.setText("Child Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 223, -1, -1));

        txtChildAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildAgeActionPerformed(evt);
            }
        });
        add(txtChildAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 223, 132, -1));

        jLabel4.setText("Child Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 268, -1, -1));

        jLabel10.setText("Remarks");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 299, -1, 21));
        add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 300, 134, -1));

        jLabel12.setText("Disease Period (in months)");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 338, -1, 21));
        add(txtDiseasePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 340, 134, -1));

        jLabel6.setText("Full Name of Parent");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 458, -1, -1));
        add(txtFullNameParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 455, 134, -1));

        jLabel9.setText("Mobile Number of Parent");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 492, -1, 21));
        add(txtMobileNumberParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 493, 134, -1));

        jLabel13.setText("Child Insurance Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 531, -1, 21));
        add(txtChildInsuranceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 532, 134, -1));

        jLabel14.setText("Preferred Mental HealthCare Location");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 416, -1, 21));
        add(txtPreferredMentalHealthCareLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 417, 134, -1));

        jLabel15.setText("Child Physician Name");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 570, -1, 21));
        add(txtChildPhysicianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 571, 134, -1));

        jLabel16.setText("Child Physician Location");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 609, -1, 21));
        add(txtChildPhysicianLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 610, 134, -1));

        jLabel5.setText("Are you parent of the child?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 107, 135, 24));

        radioButtonYes.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(radioButtonYes);
        radioButtonYes.setText("Yes");
        add(radioButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 109, -1, -1));

        radioButtonNo.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(radioButtonNo);
        radioButtonNo.setText("No");
        radioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNoActionPerformed(evt);
            }
        });
        add(radioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 110, -1, -1));

        jLabel17.setText("Last Checkup Date");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 636, -1, 21));

        jLabel18.setText("Mental Health Diagnosis Type");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 377, -1, 21));
        add(txtMentalHealthDiagnosisType, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 378, 134, -1));

        btnSubmitRequest.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setContentAreaFilled(false);
        btnSubmitRequest.setOpaque(true);
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 686, 136, 49));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 637, 134, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Child Mental HealthCare Service Request Form");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 51, -1, -1));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 55, 100, 34));

        btnBoy.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup2.add(btnBoy);
        btnBoy.setText("Boy");
        add(btnBoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 260, -1, -1));

        btnGirl.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup2.add(btnGirl);
        btnGirl.setText("Girl");
        add(btnGirl, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        
        //validate input
        if ((!btnBoy.isEnabled() && !btnGirl.isEnabled()) || txtChildFullName.getText().isEmpty() || txtChildAge.getText().isEmpty()
                || txtChildLocation.getText().isEmpty()
                || txtDiseasePeriod.getText().isEmpty()
                ){
            JOptionPane.showMessageDialog(null, "Child Name, Age, Location, Gender, Disease period cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if ((!radioButtonYes.isEnabled() && !radioButtonNo.isEnabled()) || txtFullNameParent.getText().isEmpty() || txtMobileNumberParent.getText().isEmpty()
                || txtPreferredMentalHealthCareLocation.getText().isEmpty() || jDateChooser1.getDate().toString().isEmpty()
                || txtChildPhysicianLocation.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean isValid = Validator.getInstance().validateEmailAddr(txtMobileNumberParent.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Please enter email address in format - a@b.c", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //validate diseasePeriod
        isValid = Validator.getInstance().validateAllDigits(txtDiseasePeriod.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Please enter valid disease period in number of months", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveChildMentalHealthForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(childMentalHealthAttributes);
        entity.getWorkQueue().addWorkRequest(childMentalHealthAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemUserWorkAreaJPanel workArea = (SystemUserWorkAreaJPanel) component;
        workArea.setVisible(true);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void radioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonNoActionPerformed

    private void txtChildAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioButtonNo;
    private javax.swing.JRadioButton radioButtonYes;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildFullName;
    private javax.swing.JTextField txtChildInsuranceNumber;
    private javax.swing.JTextField txtChildLocation;
    private javax.swing.JTextField txtChildPhysicianLocation;
    private javax.swing.JTextField txtChildPhysicianName;
    private javax.swing.JTextField txtDiseasePeriod;
    private javax.swing.JTextField txtFullNameParent;
    private javax.swing.JTextField txtMentalHealthDiagnosisType;
    private javax.swing.JTextField txtMobileNumberParent;
    private javax.swing.JTextField txtPreferredMentalHealthCareLocation;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables

    private void saveChildMentalHealthForm() {
        childMentalHealthAttributes.setChildFullName(
        Optional.of(txtChildFullName.getText()).orElse(""));

        if (btnBoy.isEnabled()) {
            childMentalHealthAttributes.setChildGender("Male");
        } else {
            childMentalHealthAttributes.setChildGender("Female");
        }
        
        childMentalHealthAttributes.setChildInsuranceNumber(
        Optional.of(txtChildInsuranceNumber.getText()).orElse(""));
        childMentalHealthAttributes.setChildLocation(
        Optional.of(txtChildLocation.getText()).orElse(""));
        childMentalHealthAttributes.setChildPhysicianName(
        Optional.of(txtChildPhysicianName.getText()).orElse(""));
        childMentalHealthAttributes.setChildPhysicianLocation(
        Optional.of(txtChildPhysicianName.getText()).orElse(""));
        
        if (radioButtonYes.isEnabled()) {
            childMentalHealthAttributes.setParentMobileNumber(user.getMobileNumber());
            childMentalHealthAttributes.setParentFullName(user.getFirstName() + " " + user.getLastName());
        }
        
        childMentalHealthAttributes.setParentMobileNumber(
        Optional.of(txtMobileNumberParent.getText()).orElse(""));
        childMentalHealthAttributes.setParentFullName(
        Optional.of(txtFullNameParent.getText()).orElse(""));
        childMentalHealthAttributes.setRemarks(Optional.of(txtRemarks.getText()).orElse(""));
        childMentalHealthAttributes.setPreferredHealthCareLocation(
        Optional.of(txtPreferredMentalHealthCareLocation.getText()).orElse(""));
        childMentalHealthAttributes.setTypeOfDisease("Mental Health");
        childMentalHealthAttributes.setDiseasePeriod(Integer.parseInt(txtDiseasePeriod.getText()));
        
        childMentalHealthAttributes.setLastCheckUpDate(
                Validator.getInstance().convertStringToDate(jDateChooser1.getDate().toString()));
        childMentalHealthAttributes.setMentalHealthDiagnosisType(
                Optional.of(txtMentalHealthDiagnosisType.getText()).orElse(""));
        
        String age = txtChildAge.getText();
        if (age != null) {
            childMentalHealthAttributes.setChildAge(Integer.parseInt(age));
        }        
    }
    
    private void saveWorkRequest() {
        childMentalHealthAttributes.setSender(user);
        childMentalHealthAttributes.setReceiver(organization.getOrganizationAdmin());
        childMentalHealthAttributes.setRequestDate(LocalDateTime.now());
        childMentalHealthAttributes.setOrganizationId(organization.getOrganizationId());
        childMentalHealthAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        childMentalHealthAttributes.setStatus(Status.StatusType.NEW.getValue());
    }
}
