/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildAdoption;

import Business.ChildAdoption.ChildAdoptionAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Users.User;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class ChildAdoptionRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private ChildAdoptionAttributes childAdoptionAttributes;

    /**
     * Creates new form ChildAdoptionRequestForm
     */
    public ChildAdoptionRequestForm() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        childAdoptionAttributes = new ChildAdoptionAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtChildLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtChildFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnBack2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Child Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        add(txtChildLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Child Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));
        add(txtChildFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Child Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        add(txtChildAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Child Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Remarks");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, 21));
        add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 140, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ethnicity");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, 21));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Race");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, 21));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Preferred Agency Location");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 21));

        txtPreferredAgencyLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreferredAgencyLocationActionPerformed(evt);
            }
        });
        add(txtPreferredAgencyLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 140, 30));

        btnSubmitRequest.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setContentAreaFilled(false);
        btnSubmitRequest.setOpaque(true);
        btnSubmitRequest.setPreferredSize(new java.awt.Dimension(210, 34));
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 130, -1));

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Child Adoption Request Form");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Irish", "Moroccan", "Caucasian", "Nigerian", "Asian Indian", "Chinese", "Korean", " " }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 140, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "African American", "Native American / Alaskan Native", "Pacific Islander", "Asian", "Native Hawaian", " " }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 140, 30));

        btnBack2.setBackground(new java.awt.Color(217, 180, 74));
        btnBack2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("<< Back");
        btnBack2.setContentAreaFilled(false);
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 40));

        jRadioButton1.setBackground(new java.awt.Color(172, 208, 192));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(172, 208, 192));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreferredAgencyLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreferredAgencyLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreferredAgencyLocationActionPerformed

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
         //save form
        saveAdoptionRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(childAdoptionAttributes);
        entity.getWorkQueue().addWorkRequest(childAdoptionAttributes);
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected() ){
            childAdoptionAttributes.setChildGender(jRadioButton1.getText());
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected() ){
            childAdoptionAttributes.setChildGender(jRadioButton2.getText());
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildFullName;
    private javax.swing.JTextField txtChildLocation;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables

    private void saveAdoptionRequestForm() {
        childAdoptionAttributes.setChildFullName(txtChildFullName.getText());
        childAdoptionAttributes.setChildAge(Integer.parseInt(txtChildAge.getText()));
        childAdoptionAttributes.setChildLocation(txtChildLocation.getText());
        childAdoptionAttributes.setEthnicity((String) jComboBox1.getSelectedItem());
        childAdoptionAttributes.setRace((String) jComboBox2.getSelectedItem());
        childAdoptionAttributes.setPreferredAgencyLocation(txtPreferredAgencyLocation.getText());
        childAdoptionAttributes.setRemarks(txtRemarks.getText());
    }

    private void saveWorkRequest() {
        childAdoptionAttributes.setSender(user);
        childAdoptionAttributes.setReceiver(organization.getOrganizationAdmin());
        childAdoptionAttributes.setRequestDate(LocalDateTime.now());
        childAdoptionAttributes.setOrganizationId(organization.getOrganizationId());
        childAdoptionAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        childAdoptionAttributes.setStatus(Status.StatusType.NEW.getValue());
    }

}
