/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdoptionServicesHead;

import Business.ChildAdoption.ChildAdoptionAttributes;
import Business.ChildMaltreatment.ChildMaltreatmentAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class AdoptionServicesHeadWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;

    /**
     * Creates new form AdoptionServicesHeadWorkArea
     */
    public AdoptionServicesHeadWorkArea(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        populateAdoptionHeadRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblChildDetails2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAdoptionHeadWorkRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRequestMoreDetails1 = new javax.swing.JButton();
        btnAssignToChildWelfareOfficer3 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChildDetails2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Age", "Location", "Ethnicity", "Race"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblChildDetails2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 401, 752, 42));

        tblAdoptionHeadWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Date", "Status", "Remarks", "Preferred Agency Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblAdoptionHeadWorkRequest);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 212, 752, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Child Details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 368, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Work Requests: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnRequestMoreDetails1.setBackground(new java.awt.Color(217, 180, 74));
        btnRequestMoreDetails1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnRequestMoreDetails1.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestMoreDetails1.setText("Request More Details");
        btnRequestMoreDetails1.setContentAreaFilled(false);
        btnRequestMoreDetails1.setOpaque(true);
        btnRequestMoreDetails1.setPreferredSize(new java.awt.Dimension(210, 34));
        btnRequestMoreDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMoreDetails1ActionPerformed(evt);
            }
        });
        add(btnRequestMoreDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 537, 232, -1));

        btnAssignToChildWelfareOfficer3.setBackground(new java.awt.Color(217, 180, 74));
        btnAssignToChildWelfareOfficer3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnAssignToChildWelfareOfficer3.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToChildWelfareOfficer3.setText("Assign to Child Welfare Officer");
        btnAssignToChildWelfareOfficer3.setContentAreaFilled(false);
        btnAssignToChildWelfareOfficer3.setOpaque(true);
        btnAssignToChildWelfareOfficer3.setPreferredSize(new java.awt.Dimension(210, 34));
        btnAssignToChildWelfareOfficer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToChildWelfareOfficer3ActionPerformed(evt);
            }
        });
        add(btnAssignToChildWelfareOfficer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 537, 232, -1));

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Adoption Service Head WorkArea");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 43, 408, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestMoreDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMoreDetails1ActionPerformed

    }//GEN-LAST:event_btnRequestMoreDetails1ActionPerformed

    private void btnAssignToChildWelfareOfficer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToChildWelfareOfficer3ActionPerformed
        ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblAdoptionHeadWorkRequest.getValueAt(tblAdoptionHeadWorkRequest.getSelectedRow(), 0);

        for (User user : entity.getUserDirectory().getUserList()) {
            if (user.getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin) {
                cma.setReceiver(user);
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Assigned To ChildWelfare Admin", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignToChildWelfareOfficer3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToChildWelfareOfficer3;
    private javax.swing.JButton btnRequestMoreDetails1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAdoptionHeadWorkRequest;
    private javax.swing.JTable tblChildDetails2;
    // End of variables declaration//GEN-END:variables

    private void populateAdoptionHeadRequests() {
        DefaultTableModel delModel = (DefaultTableModel) tblAdoptionHeadWorkRequest.getModel();
        delModel.setRowCount(0);
        ArrayList<WorkRequest> workRequestList = organization.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : workRequestList) {
            if (workRequest.getStatus().equalsIgnoreCase(Status.StatusType.NEW.getValue())
                    || workRequest.getStatus().equalsIgnoreCase(Status.StatusType.INPROGRESS.getValue())) {

                ChildAdoptionAttributes cha = (ChildAdoptionAttributes) workRequest;
                Object[] row = new Object[5];
                row[0] = cha;
                row[1] = cha.getRequestDate();
                row[2] = cha.getStatus();
                row[3] = cha.getRemarks();
                row[4] = cha.getPreferredAgencyLocation();
                delModel.addRow(row);
            }
        }

        tblAdoptionHeadWorkRequest.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                populateDetailsTable();
            }
        });
    }

    private void populateDetailsTable() {
        try {
            ChildAdoptionAttributes cha = (ChildAdoptionAttributes) tblAdoptionHeadWorkRequest.getValueAt(tblAdoptionHeadWorkRequest.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblChildDetails2.getModel();
            model.setRowCount(0);
            Object[] row = new Object[6];
            row[0] = cha.getChildFullName();
            row[1] = cha.getChildGender();
            row[2] = cha.getChildAge();
            row[3] = cha.getChildLocation();
            row[4] = cha.getEthnicity();
            row[5] = cha.getRace();
            model.addRow(row);

        } catch (Exception e) {
            return;
        }
    }
}
