/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.YouthCareServices;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import Business.YouthCare.YouthCareAttributes;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemUser.SystemUserWorkAreaJPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class YouthCareServicesRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private YouthCareAttributes youthCareAttributes;

    /**
     * Creates new form YouthCareServicesRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param enterprise
     * @param user
     * @param organization
     */
    public YouthCareServicesRequestForm(JPanel userProcessContainer, Entity entity, Enterprise enterprise,
            User user, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        youthCareAttributes = new YouthCareAttributes();
        Date date = new Date();
        jDateChooser1.setMaxSelectableDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLegalGuardianName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLegalGuardianMobile = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSchoolName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPreviousYouthcareAgency = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSchoolGrade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();
        btnSubmitRequest1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 180, 30));

        jLabel2.setText("Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        txtFullName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 180, 30));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel4.setText("Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        txtRemarks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 180, 30));

        jLabel10.setText("Remarks");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, 21));

        jLabel11.setText("Date Of Birth");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, 21));

        txtLegalGuardianName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtLegalGuardianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 180, 30));

        jLabel12.setText("Legal Guardian Name");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, 21));

        txtLegalGuardianMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtLegalGuardianMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 180, 30));

        jLabel14.setText("Preferred Agency Location");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 810, -1, 21));

        txtPreferredAgencyLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtPreferredAgencyLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 800, 180, 30));

        jLabel13.setText("Legal Guardian Mobile");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, 21));

        txtSchoolName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 180, 30));

        jLabel15.setText("Previous YouthCare Agency");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 740, -1, 21));

        txtPreviousYouthcareAgency.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtPreviousYouthcareAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 740, 180, 30));

        jLabel16.setText("School Name");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, -1, 21));

        txtSchoolGrade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtSchoolGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 180, 30));

        jLabel17.setText("School Grade");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, -1, 21));

        txtLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 180, 30));

        btnBoy.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnBoy);
        btnBoy.setText("Boy");
        add(btnBoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        btnGirl.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnGirl);
        btnGirl.setText("Girl");
        add(btnGirl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        btnSubmitRequest1.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest1.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest1.setText("Submit Request");
        btnSubmitRequest1.setContentAreaFilled(false);
        btnSubmitRequest1.setOpaque(true);
        btnSubmitRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequest1ActionPerformed(evt);
            }
        });
        add(btnSubmitRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 880, 220, 50));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Youth Care Service Request Form");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 400, -1));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequest1ActionPerformed
        //validations for emtpy fields
        if (txtLegalGuardianName.getText().isEmpty() || txtLegalGuardianMobile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Legal Guardian name and mobile cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtFullName.getText().isEmpty() || txtAge.getText().isEmpty() || txtLocation.getText().isEmpty()
             || jDateChooser1.getDate().toString().isEmpty()   || (!btnBoy.isEnabled() && !btnGirl.isEnabled())) {
            JOptionPane.showMessageDialog(null, "Name, Date of birth, age, gender cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean isValid;
        isValid = Validator.getInstance().validateAllDigits(txtAge.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Age should consists of digits only", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveYouthCareRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(youthCareAttributes);
        entity.getWorkQueue().addWorkRequest(youthCareAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSubmitRequest1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemUserWorkAreaJPanel workArea = (SystemUserWorkAreaJPanel) component;
        workArea.setVisible(true);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JButton btnSubmitRequest1;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtLegalGuardianMobile;
    private javax.swing.JTextField txtLegalGuardianName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtPreviousYouthcareAgency;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtSchoolGrade;
    private javax.swing.JTextField txtSchoolName;
    // End of variables declaration//GEN-END:variables

    private void saveYouthCareRequestForm() {

        youthCareAttributes.setFullName(txtFullName.getText());
        youthCareAttributes.setAge(Integer.parseInt(txtAge.getText()));
        youthCareAttributes.setLocation(txtLocation.getText());
        youthCareAttributes.setPreferredAgencyLocation(
                Optional.of(txtPreferredAgencyLocation.getText()).orElse(""));
        youthCareAttributes.setRemarks(
                Optional.of(txtRemarks.getText()).orElse(""));
        youthCareAttributes.setDateOfBirth(LocalDate.parse(jDateChooser1.getDate().toString()));
        youthCareAttributes.setLegalGuardianName(txtLegalGuardianName.getText());
        youthCareAttributes.setLegalGuardianMobile(txtLegalGuardianMobile.getText());
        youthCareAttributes.setSchoolName(
                Optional.of(txtSchoolName.getText()).orElse(""));
        youthCareAttributes.setGrade(
                Optional.of(txtSchoolGrade.getText()).orElse(""));
        youthCareAttributes.setPreviousYouthCareAgency(
                Optional.of(txtPreviousYouthcareAgency.getText()).orElse(""));

        if (btnBoy.isEnabled()) {
            youthCareAttributes.setGender("Male");
        } else {
            youthCareAttributes.setGender("Female");
        }

    }

    private void saveWorkRequest() {

        youthCareAttributes.setSender(user);
        youthCareAttributes.setReceiver(organization.getOrganizationAdmin());
        youthCareAttributes.setRequestDate(LocalDateTime.now());
        youthCareAttributes.setOrganizationId(organization.getOrganizationId());
        youthCareAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        youthCareAttributes.setStatus(Status.StatusType.NEW.getValue());

    }
}
