/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.YouthCareServices;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.YouthCare.YouthCareAttributes;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class YouthCareServicesRequestForm extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private YouthCareAttributes youthCareAttributes;

    /**
     * Creates new form YouthCareServicesRequestForm
     */
    public YouthCareServicesRequestForm(JPanel userProcessContainer, Entity entity, Enterprise enterprise, 
            User user, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        youthCareAttributes = new YouthCareAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSubmitRequest1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDoB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLegalGuardianName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLegalGuardianMobile = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSchoolName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPreviousYouthcareAgency = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSchoolGrade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();

        btnSubmitRequest1.setText("Submit Request");
        btnSubmitRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequest1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Location");

        txtAge.setText("jTextField1");

        jLabel2.setText("Full Name");

        txtFullName.setText("jTextField1");

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        txtRemarks.setText("jTextField1");

        jLabel10.setText("Remarks");

        txtDoB.setText("jTextField5");

        jLabel11.setText("Date Of Birth");

        txtLegalGuardianName.setText("jTextField5");

        jLabel12.setText("Legal Guardian Name");

        txtLegalGuardianMobile.setText("jTextField5");

        jLabel14.setText("Preferred Agency Location");

        txtPreferredAgencyLocation.setText("jTextField5");

        jLabel13.setText("Legal Guardian Mobile");

        txtSchoolName.setText("jTextField5");

        jLabel15.setText("Previous YouthCare Agency");

        txtPreviousYouthcareAgency.setText("jTextField5");

        jLabel16.setText("School Name");

        txtSchoolGrade.setText("jTextField5");

        jLabel17.setText("School Grade");

        txtLocation.setText("jTextField1");

        buttonGroup1.add(btnBoy);
        btnBoy.setText("Boy");

        buttonGroup1.add(btnGirl);
        btnGirl.setText("Girl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSchoolGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreferredAgencyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreviousYouthcareAgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBoy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGirl))
                            .addComponent(txtLegalGuardianMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnSubmitRequest1)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBoy)
                        .addComponent(btnGirl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchoolGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreviousYouthcareAgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreferredAgencyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSubmitRequest1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequest1ActionPerformed

        //validations for emtpy fields
        if (txtLegalGuardianName.getText().isEmpty() || txtLegalGuardianMobile.getText().isEmpty() || txtAge.getText().isEmpty()
                || (!btnBoy.isEnabled() && !btnGirl.isEnabled())) {
            JOptionPane.showMessageDialog(null, "Legal Guardian details, Date of birth, full name, age, gender cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        //save form
        saveYouthCareRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(youthCareAttributes);
        entity.getWorkQueue().addWorkRequest(youthCareAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitRequest1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JButton btnSubmitRequest1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDoB;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtLegalGuardianMobile;
    private javax.swing.JTextField txtLegalGuardianName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtPreviousYouthcareAgency;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtSchoolGrade;
    private javax.swing.JTextField txtSchoolName;
    // End of variables declaration//GEN-END:variables

    private void saveYouthCareRequestForm() {
        
        youthCareAttributes.setFullName(txtFullName.getText());
        youthCareAttributes.setAge(Integer.parseInt(txtAge.getText()));
        youthCareAttributes.setLocation(txtLocation.getText());
        youthCareAttributes.setPreferredAgencyLocation(txtPreferredAgencyLocation.getText());
        youthCareAttributes.setRemarks(txtRemarks.getText());
        youthCareAttributes.setDateOfBirth(LocalDate.parse(txtDoB.getText()));
        youthCareAttributes.setLegalGuardianName(txtLegalGuardianName.getText());
        youthCareAttributes.setLegalGuardianMobile(txtLegalGuardianMobile.getText());
        youthCareAttributes.setSchoolName(txtSchoolName.getText());
        youthCareAttributes.setGrade(txtSchoolGrade.getText());
        youthCareAttributes.setPreviousYouthCareAgency(txtPreviousYouthcareAgency.getText());
        
        if(btnBoy.isEnabled()){
            youthCareAttributes.setGender("Male");
        }
        else{
            youthCareAttributes.setGender("Female");
        }
        
    }

    private void saveWorkRequest() {
        
        youthCareAttributes.setSender(user);
        youthCareAttributes.setReceiver(organization.getOrganizationAdmin());
        youthCareAttributes.setRequestDate(LocalDateTime.now());
        youthCareAttributes.setOrganizationId(organization.getOrganizationId());
        youthCareAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        youthCareAttributes.setStatus(Status.StatusType.NEW.getValue());
        
    }
}
