/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SafetyHeadWorkArea;

import Business.ChildMaltreatment.ChildMaltreatmentAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class SafetyHeadAdminWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;

    /**
     * Creates new form SafetyHeadAdminWorkArea
     *
     * @param userProcessContainer
     * @param entity
     * @param organization
     * @param enterprise
     * @param user
     */
    public SafetyHeadAdminWorkArea(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        populateSafetyHeadRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVictimDetaiils = new javax.swing.JTable();
        btnAssignToChildWelfareOfficer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSafetyHeadWorkRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReporterDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRequestMoreDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(178, 208, 192));

        tblVictimDetaiils.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Age", "Location", "Relationship with alleged offender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVictimDetaiils);
        if (tblVictimDetaiils.getColumnModel().getColumnCount() > 0) {
            tblVictimDetaiils.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(2).setHeaderValue("Age");
            tblVictimDetaiils.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(4).setHeaderValue("Relationship with alleged offender");
        }

        btnAssignToChildWelfareOfficer.setText("Assign to Child Welfare Officer");
        btnAssignToChildWelfareOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToChildWelfareOfficerActionPerformed(evt);
            }
        });

        tblSafetyHeadWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Date", "Status", "Type of Abuse", "Remarks"
            }
        ));
        jScrollPane2.setViewportView(tblSafetyHeadWorkRequest);
        if (tblSafetyHeadWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(2).setHeaderValue("Relationship with alleged offender");
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(3).setHeaderValue("Age");
        }

        jLabel1.setText("Victim Details:");

        jLabel2.setText("Offender Details:");

        tblReporterDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Gender", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblReporterDetails);
        if (tblReporterDetails.getColumnModel().getColumnCount() > 0) {
            tblReporterDetails.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblReporterDetails.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jLabel3.setText("Work Requests: ");

        btnRequestMoreDetails.setText("Request More Details");
        btnRequestMoreDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMoreDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssignToChildWelfareOfficer)
                                .addGap(67, 67, 67)
                                .addComponent(btnRequestMoreDetails)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignToChildWelfareOfficer)
                    .addComponent(btnRequestMoreDetails))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToChildWelfareOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToChildWelfareOfficerActionPerformed
        ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);

        for (User user : entity.getUserDirectory().getUserList()) {
            if (user.getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin) {
                cma.setReceiver(user);
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Assigned To ChildWelfare Admin", "Success", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnAssignToChildWelfareOfficerActionPerformed

    private void btnRequestMoreDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMoreDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestMoreDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToChildWelfareOfficer;
    private javax.swing.JButton btnRequestMoreDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblReporterDetails;
    private javax.swing.JTable tblSafetyHeadWorkRequest;
    private javax.swing.JTable tblVictimDetaiils;
    // End of variables declaration//GEN-END:variables

    private void populateSafetyHeadRequests() {

        DefaultTableModel delModel = (DefaultTableModel) tblSafetyHeadWorkRequest.getModel();
        delModel.setRowCount(0);
        ArrayList<WorkRequest> workRequestList = organization.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : workRequestList) {
            if (workRequest.getStatus().equalsIgnoreCase(Status.StatusType.NEW.getValue())
                    || workRequest.getStatus().equalsIgnoreCase(Status.StatusType.INPROGRESS.getValue())) {

                ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) workRequest;
                Object[] row = new Object[5];
                row[0] = cma;
                row[1] = cma.getRequestDate();
                row[2] = cma.getStatus();
                row[3] = cma.getTypeOfAbuse();
                row[4] = cma.getRemarks();
                delModel.addRow(row);
            }
        }

        tblSafetyHeadWorkRequest.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                populateDetailsTable();
            }
        });
    }

    private void populateDetailsTable() {
        populateVictimTable();
        populateReporterTable();
    }

    private void populateVictimTable() {
        try {
            ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblVictimDetaiils.getModel();
            model.setRowCount(0);
            Object[] row = new Object[5];
            row[0] = cma.getFullNameVictim();
            row[1] = cma.getGenderVictim();
            row[2] = cma.getAgeVictim();
            row[3] = cma.getLocationVictim();
            row[4] = cma.getRelationshipVictimOffender();
            model.addRow(row);

        } catch (Exception e) {
            return;
        }
    }

    private void populateReporterTable() {
        try {
            ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblReporterDetails.getModel();
            model.setRowCount(0);
            Object[] row = new Object[4];
            row[0] = cma.getOffenderName();
            row[1] = cma.getOffenderLocation();
            row[2] = cma.getOffenderGender();
            row[3] = cma.getOffenderDescription();
            model.addRow(row);
        } catch (Exception e) {
            return;
        }
    }
}
