/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SafetyHeadWorkArea;

import Business.ChildMaltreatment.ChildMaltreatmentAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class SafetyHeadAdminWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;

    /**
     * Creates new form SafetyHeadAdminWorkArea
     *
     * @param userProcessContainer
     * @param entity
     * @param organization
     * @param enterprise
     * @param user
     */
    public SafetyHeadAdminWorkArea(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        populateSafetyHeadRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVictimDetaiils = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSafetyHeadWorkRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReporterDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRequestMoreDetails = new javax.swing.JButton();
        btnAssignToChildWelfareOfficer = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(178, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVictimDetaiils.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Age", "Location", "Relationship with alleged offender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVictimDetaiils);
        if (tblVictimDetaiils.getColumnModel().getColumnCount() > 0) {
            tblVictimDetaiils.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(2).setHeaderValue("Age");
            tblVictimDetaiils.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblVictimDetaiils.getColumnModel().getColumn(4).setHeaderValue("Relationship with alleged offender");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 292, 1023, 42));

        tblSafetyHeadWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Date", "Status", "Type of Abuse", "Remarks"
            }
        ));
        jScrollPane2.setViewportView(tblSafetyHeadWorkRequest);
        if (tblSafetyHeadWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(2).setHeaderValue("Relationship with alleged offender");
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblSafetyHeadWorkRequest.getColumnModel().getColumn(3).setHeaderValue("Age");
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 1023, 105));

        jLabel1.setText("Victim Details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, -1, -1));

        jLabel2.setText("Offender Details:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 376, -1, -1));

        tblReporterDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Gender", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblReporterDetails);
        if (tblReporterDetails.getColumnModel().getColumnCount() > 0) {
            tblReporterDetails.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblReporterDetails.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 407, 1023, 42));

        jLabel3.setText("Work Requests: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        btnRequestMoreDetails.setBackground(new java.awt.Color(217, 180, 74));
        btnRequestMoreDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnRequestMoreDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestMoreDetails.setText("Request More Details");
        btnRequestMoreDetails.setContentAreaFilled(false);
        btnRequestMoreDetails.setOpaque(true);
        btnRequestMoreDetails.setPreferredSize(new java.awt.Dimension(210, 34));
        btnRequestMoreDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMoreDetailsActionPerformed(evt);
            }
        });
        add(btnRequestMoreDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 504, 172, -1));

        btnAssignToChildWelfareOfficer.setBackground(new java.awt.Color(217, 180, 74));
        btnAssignToChildWelfareOfficer.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnAssignToChildWelfareOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToChildWelfareOfficer.setText("Assign to Child Welfare Officer");
        btnAssignToChildWelfareOfficer.setContentAreaFilled(false);
        btnAssignToChildWelfareOfficer.setOpaque(true);
        btnAssignToChildWelfareOfficer.setPreferredSize(new java.awt.Dimension(210, 34));
        btnAssignToChildWelfareOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToChildWelfareOfficerActionPerformed(evt);
            }
        });
        add(btnAssignToChildWelfareOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 504, 232, -1));

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Safety Head WorkArea");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 31, 408, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestMoreDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMoreDetailsActionPerformed

    }//GEN-LAST:event_btnRequestMoreDetailsActionPerformed

    private void btnAssignToChildWelfareOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToChildWelfareOfficerActionPerformed
        ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);

        for (User user : entity.getUserDirectory().getUserList()) {
            if (user.getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin) {
                cma.setReceiver(user);
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Assigned To ChildWelfare Admin", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignToChildWelfareOfficerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToChildWelfareOfficer;
    private javax.swing.JButton btnRequestMoreDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReporterDetails;
    private javax.swing.JTable tblSafetyHeadWorkRequest;
    private javax.swing.JTable tblVictimDetaiils;
    // End of variables declaration//GEN-END:variables

    private void populateSafetyHeadRequests() {

        DefaultTableModel delModel = (DefaultTableModel) tblSafetyHeadWorkRequest.getModel();
        delModel.setRowCount(0);
        ArrayList<WorkRequest> workRequestList = organization.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : workRequestList) {
            if (workRequest.getStatus().equalsIgnoreCase(Status.StatusType.NEW.getValue())
                    || workRequest.getStatus().equalsIgnoreCase(Status.StatusType.INPROGRESS.getValue())) {

                ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) workRequest;
                Object[] row = new Object[5];
                row[0] = cma;
                row[1] = cma.getRequestDate();
                row[2] = cma.getStatus();
                row[3] = cma.getTypeOfAbuse();
                row[4] = cma.getRemarks();
                delModel.addRow(row);
            }
        }

        tblSafetyHeadWorkRequest.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                populateDetailsTable();
            }
        });
    }

    private void populateDetailsTable() {
        populateVictimTable();
        populateReporterTable();
    }

    private void populateVictimTable() {
        try {
            ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblVictimDetaiils.getModel();
            model.setRowCount(0);
            Object[] row = new Object[5];
            row[0] = cma.getFullNameVictim();
            row[1] = cma.getGenderVictim();
            row[2] = cma.getAgeVictim();
            row[3] = cma.getLocationVictim();
            row[4] = cma.getRelationshipVictimOffender();
            model.addRow(row);

        } catch (Exception e) {
            return;
        }
    }

    private void populateReporterTable() {
        try {
            ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblSafetyHeadWorkRequest.getValueAt(tblSafetyHeadWorkRequest.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblReporterDetails.getModel();
            model.setRowCount(0);
            Object[] row = new Object[4];
            row[0] = cma.getOffenderName();
            row[1] = cma.getOffenderLocation();
            row[2] = cma.getOffenderGender();
            row[3] = cma.getOffenderDescription();
            model.addRow(row);
        } catch (Exception e) {
            return;
        }
    }
}
