/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Role.Role;
import Business.Users.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class CreateUpdateEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel enterprisePanel;
    private Entity entity;
    private User user;
    private static final int CREATE_OPERATION = 0;
    private static final int UPDATE_OPERATION = 1;
    private int operationId;
    private Enterprise enterprise;

    /**
     * Creates new form CreateUpdateEnterpriseJPanel
     */
    public CreateUpdateEnterpriseJPanel(JPanel enterprisePanel, User user, Entity entity, int operationId, Enterprise enterprise) {
        initComponents();
        this.enterprisePanel = enterprisePanel;
        this.entity = entity;
        this.user = user;
        this.operationId = operationId;
        this.enterprise = enterprise;
        loadData();
    }

    private void loadData() {
        if (operationId == UPDATE_OPERATION) {
            btnCreate.setText("Update");
            lblTitle.setText("Update Enterprise");
            txtEnterpriseName.setText(enterprise.getEnterpriseName());
            txtRegistrationNo.setText(enterprise.getEnterpriseRegistrationNo());
            txtEnterpriseDesc.setText(enterprise.getEnterpriseDesciption());
            txtRegistrationNo.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        lblEnterpriseeDesc = new javax.swing.JLabel();
        txtEnterpriseDesc = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEnterpriseNo = new javax.swing.JLabel();
        txtRegistrationNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Enterprises");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 74, 280, 49));

        lblEnterpriseName.setText("Enterprise Name:");
        add(lblEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 185, 168, 34));

        txtEnterpriseName.setSelectionColor(new java.awt.Color(117, 177, 169));
        add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 183, 155, 38));

        lblEnterpriseeDesc.setText("Enterprise Description");
        add(lblEnterpriseeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 234, 168, 34));
        add(txtEnterpriseDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 232, 155, 38));

        btnCreate.setBackground(new java.awt.Color(217, 180, 74));
        btnCreate.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.setContentAreaFilled(false);
        btnCreate.setOpaque(true);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 367, 115, 49));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" <<Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 74, 115, 49));

        lblEnterpriseNo.setText("Enterprise Registration No");
        add(lblEnterpriseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 283, 168, 34));
        add(txtRegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 281, 155, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        //Validate for emtpy fields
        if (txtEnterpriseName.getText().isEmpty() || txtEnterpriseDesc.getText().isEmpty() || txtRegistrationNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields ", "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        switch (operationId) {
            case CREATE_OPERATION:
                //validate for registration number
                for (Enterprise er : entity.getEnterpriseDirectory().getEnterpriseList()) {
                    if (er.getEnterpriseRegistrationNo().equals(txtRegistrationNo.getText())) {
                        JOptionPane.showMessageDialog(null, "Registration Number Already Exists ", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                entity.getEnterpriseDirectory().createEnterprise(txtEnterpriseName.getText(), txtEnterpriseDesc.getText(), txtRegistrationNo.getText());
                JOptionPane.showMessageDialog(null, "New Enterprise Registered", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnBack.doClick();
                break;
            case UPDATE_OPERATION:
                for (Enterprise er : entity.getEnterpriseDirectory().getEnterpriseList()) {
                    if (er.getEnterpriseRegistrationNo().equals(enterprise.getEnterpriseRegistrationNo())) {
                        enterprise.setEnterpriseName(txtEnterpriseName.getText());
                        enterprise.setEnterpriseDesciption(txtEnterpriseDesc.getText());
                        enterprise.setEnterpriseRegistrationNo(txtRegistrationNo.getText());
                    }
                }
                JOptionPane.showMessageDialog(null, "Enterprise Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnBack.doClick();

                break;
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        enterprisePanel.remove(this);
        Component[] componentArray = enterprisePanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminEnterprisesWorkArea workArea = (SysAdminEnterprisesWorkArea) component;
        workArea.populateTable();
        CardLayout layout = (CardLayout) enterprisePanel.getLayout();
        layout.previous(enterprisePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseNo;
    private javax.swing.JLabel lblEnterpriseeDesc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEnterpriseDesc;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtRegistrationNo;
    // End of variables declaration//GEN-END:variables
}
