/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.InternationalOrganizationCollaborationHead;

import Business.ChildMaltreatment.ChildMaltreatmentAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.InternationalOrganizationCollaboration.InternationalOrganizationCollaborationAttributes;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class InternationalOrganizationCollaborationHeadWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;

    /**
     * Creates new form InternationalOrganizationCollaborationRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param organization
     * @param enterprise
     * @param user
     */
    public InternationalOrganizationCollaborationHeadWorkArea(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        populateHealthCareHeadRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblIntOrgCollabHeadWorkArea = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblorgDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnAssignToChildWelfareOfficer = new javax.swing.JButton();
        btnRequestMoreDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblIntOrgCollabHeadWorkArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Date", "Status", "Remarks", "Preferred Agency Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblIntOrgCollabHeadWorkArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 747, 91));

        jLabel2.setText("Organization Details:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));

        tblorgDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "International ID", "City", "Country", "Type", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblorgDetails);
        if (tblorgDetails.getColumnModel().getColumnCount() > 0) {
            tblorgDetails.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, 747, 42));

        jLabel3.setText("Work Requests: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("International Collaboration Head WorkArea");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 37, -1, -1));

        btnAssignToChildWelfareOfficer.setBackground(new java.awt.Color(217, 180, 74));
        btnAssignToChildWelfareOfficer.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnAssignToChildWelfareOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToChildWelfareOfficer.setText("Assign to Child Welfare Officer");
        btnAssignToChildWelfareOfficer.setContentAreaFilled(false);
        btnAssignToChildWelfareOfficer.setOpaque(true);
        btnAssignToChildWelfareOfficer.setPreferredSize(new java.awt.Dimension(210, 34));
        btnAssignToChildWelfareOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToChildWelfareOfficerActionPerformed(evt);
            }
        });
        add(btnAssignToChildWelfareOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 437, 232, -1));

        btnRequestMoreDetails.setBackground(new java.awt.Color(217, 180, 74));
        btnRequestMoreDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnRequestMoreDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestMoreDetails.setText("Request More Details");
        btnRequestMoreDetails.setContentAreaFilled(false);
        btnRequestMoreDetails.setOpaque(true);
        btnRequestMoreDetails.setPreferredSize(new java.awt.Dimension(210, 34));
        btnRequestMoreDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMoreDetailsActionPerformed(evt);
            }
        });
        add(btnRequestMoreDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 437, 172, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToChildWelfareOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToChildWelfareOfficerActionPerformed
        ChildMaltreatmentAttributes cma = (ChildMaltreatmentAttributes) tblIntOrgCollabHeadWorkArea.getValueAt(tblIntOrgCollabHeadWorkArea.getSelectedRow(), 0);

        for (User user : entity.getUserDirectory().getUserList()) {
            if (user.getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin) {
                cma.setReceiver(user);
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Assigned To ChildWelfare Admin", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignToChildWelfareOfficerActionPerformed

    private void btnRequestMoreDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMoreDetailsActionPerformed

    }//GEN-LAST:event_btnRequestMoreDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToChildWelfareOfficer;
    private javax.swing.JButton btnRequestMoreDetails;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblIntOrgCollabHeadWorkArea;
    private javax.swing.JTable tblorgDetails;
    // End of variables declaration//GEN-END:variables

    private void populateHealthCareHeadRequests() {

        DefaultTableModel delModel = (DefaultTableModel) tblIntOrgCollabHeadWorkArea.getModel();
        delModel.setRowCount(0);
        ArrayList<WorkRequest> workRequestList = organization.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : workRequestList) {
            if (workRequest.getStatus().equalsIgnoreCase(Status.StatusType.NEW.getValue())
                    || workRequest.getStatus().equalsIgnoreCase(Status.StatusType.INPROGRESS.getValue())) {

                InternationalOrganizationCollaborationAttributes cha = (InternationalOrganizationCollaborationAttributes) workRequest;
                Object[] row = new Object[6];
                row[0] = cha;
                row[1] = cha.getRequestDate();
                row[2] = cha.getStatus();
                row[3] = cha.getRemarks();
                row[4] = cha.getPreferredCollaborationCountry();
                delModel.addRow(row);
            }
        }

        tblIntOrgCollabHeadWorkArea.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                populateDetailsTable();
            }
        });
    }

    private void populateDetailsTable() {
        try {
            InternationalOrganizationCollaborationAttributes cha = (InternationalOrganizationCollaborationAttributes) tblIntOrgCollabHeadWorkArea.getValueAt(tblIntOrgCollabHeadWorkArea.getSelectedRow(), 0);
            DefaultTableModel model = (DefaultTableModel) tblorgDetails.getModel();
            model.setRowCount(0);
            Object[] row = new Object[6];
            row[0] = cha.getOrganizationName();
            row[1] = cha.getOrganizationInternationalId();
            row[2] = cha.getOrganizationCity();
            row[3] = cha.getOrganizationCountry();
            row[4] = cha.getOrganizationType();
            row[5] = cha.getOrganizationEmail();
            model.addRow(row);

        } catch (Exception e) {
            return;
        }
    }
}
