/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildWelfareAdmin;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Organizations.Organization;
import Business.Users.User;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class ChildWelfareDashboardJPanel extends javax.swing.JPanel {

    private JPanel displayPanel;
    private Entity entity;
    private User user;
    private Enterprise enterprise;

    /**
     * Creates new form ChildWelfareDashboardJPanel
     */
    public ChildWelfareDashboardJPanel(JPanel displayPanel, Entity entity, Enterprise enterprise, User user) {
        initComponents();
        this.displayPanel = displayPanel;
        this.entity = entity;
        this.user = user;
        this.enterprise = enterprise;
        loadCharts();
    }
    
    private void loadCharts(){
        pieChartJPanel.removeAll();
        pieChartJPanel.revalidate();
        // This will create the dataset
        PieDataset dataset = createDataset();
        // based on the dataset we create the chart
        JFreeChart chart = createChart(dataset, "Requests based on Organizations");
        // we put the chart into a panel
        ChartPanel chartPanel = new ChartPanel(chart);
        // default size
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 450));
        // add it to our application
        pieChartJPanel.setLayout(new BorderLayout());
        pieChartJPanel.add(chartPanel, BorderLayout.NORTH);
    }
    
    private PieDataset createDataset() {
       
       DefaultPieDataset defaultPieDataset = new DefaultPieDataset();
       ArrayList<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
       
       for(int i =0; i<orgList.size(); i++){
           defaultPieDataset.setValue(orgList.get(i).getOrganizationName(), orgList.get(i).getWorkQueue().getWorkRequestList().size());
       }
       
       return defaultPieDataset;
    }
    
    /**
     * Creates a chart
     */
    private JFreeChart createChart(PieDataset dataset, String title) {

       JFreeChart chart = ChartFactory.createPieChart3D(
                title, // chart title
                dataset, // data
                true, // include legend
                true,
                false
        );

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pieChartJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Request Chart For Organizations");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 400, 53));

        javax.swing.GroupLayout pieChartJPanelLayout = new javax.swing.GroupLayout(pieChartJPanel);
        pieChartJPanel.setLayout(pieChartJPanelLayout);
        pieChartJPanelLayout.setHorizontalGroup(
            pieChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        pieChartJPanelLayout.setVerticalGroup(
            pieChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        add(pieChartJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pieChartJPanel;
    // End of variables declaration//GEN-END:variables


}
