/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildWelfareAdmin;

import Business.ChildMaltreatment.ChildMaltreatmentAttributes;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SysAdminEnterprisesWorkArea;
import userinterface.SystemAdminWorkArea.SysAdminRolesWorkArea;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class ChildWelfareAdminWorkArea extends javax.swing.JPanel {

    private JPanel displayPanel;
    private Entity entity;
    private User user;
    private Enterprise enterprise;

    /**
     * Creates new form ChildWelfareAdminWorkArea
     */
    public ChildWelfareAdminWorkArea(JPanel displayPanel, Entity entity, Enterprise enterprise, User user) {
        initComponents();
        this.displayPanel = displayPanel;
        this.entity = entity;
        this.user = user;
        this.enterprise = enterprise;
        loadView();

    }

    private void loadView() {
        int selectedIndex = jTabbedSystemAdmin.getSelectedIndex();
        if (selectedIndex == 0 || selectedIndex == -1) {
            ChildWelfareOrganizationWorkArea childWelfareOrgWorkArea = new ChildWelfareOrganizationWorkArea(jPanelEnterprise, user, entity, enterprise);
            jPanelEnterprise.add(childWelfareOrgWorkArea);
            CardLayout cardLayout = (CardLayout) jPanelEnterprise.getLayout();
            cardLayout.next(jPanelEnterprise);
        } else if (selectedIndex == 1) {
            ChildWelfareOrgAdminRolesWorkArea adminRolesWorkArea = new ChildWelfareOrgAdminRolesWorkArea(jPanelAdminRoles, user, entity, enterprise);
            jPanelAdminRoles.add(adminRolesWorkArea);
            CardLayout cardLayout = (CardLayout) jPanelAdminRoles.getLayout();
            cardLayout.next(jPanelAdminRoles);
        } else {
            SysAdminRolesWorkArea adminRolesWorkArea = new SysAdminRolesWorkArea(jPanelWorkRequests, user, entity);
            jPanelWorkRequests.add(adminRolesWorkArea);
            CardLayout cardLayout = (CardLayout) jPanelWorkRequests.getLayout();
            cardLayout.next(jPanelWorkRequests);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedSystemAdmin = new javax.swing.JTabbedPane();
        jPanelEnterprise = new javax.swing.JPanel();
        jPanelAdminRoles = new javax.swing.JPanel();
        jPanelWorkRequests = new javax.swing.JPanel();

        setBackground(new java.awt.Color(172, 208, 192));

        jTabbedSystemAdmin.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedSystemAdmin.setToolTipText("Manage Enterprises");
        jTabbedSystemAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedSystemAdminStateChanged(evt);
            }
        });

        jPanelEnterprise.setBackground(new java.awt.Color(172, 208, 192));
        jPanelEnterprise.setPreferredSize(new java.awt.Dimension(1030, 700));
        jPanelEnterprise.setLayout(new java.awt.CardLayout());
        jTabbedSystemAdmin.addTab("Organization", new javax.swing.ImageIcon(getClass().getResource("/res/organization_logo.png")), jPanelEnterprise); // NOI18N

        jPanelAdminRoles.setBackground(new java.awt.Color(172, 208, 192));
        jPanelAdminRoles.setPreferredSize(new java.awt.Dimension(1030, 700));
        jPanelAdminRoles.setLayout(new java.awt.CardLayout());
        jTabbedSystemAdmin.addTab("Admins", new javax.swing.ImageIcon(getClass().getResource("/res/admin_logo.png")), jPanelAdminRoles); // NOI18N

        jPanelWorkRequests.setBackground(new java.awt.Color(172, 208, 192));
        jPanelWorkRequests.setLayout(new java.awt.CardLayout());
        jTabbedSystemAdmin.addTab("Work Requests", new javax.swing.ImageIcon(getClass().getResource("/res/task_management.png")), jPanelWorkRequests); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1531, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedSystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedSystemAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedSystemAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedSystemAdminStateChanged
        // TODO add your handling code here:
        if (entity != null) {
            loadView();
        }
    }//GEN-LAST:event_jTabbedSystemAdminStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAdminRoles;
    private javax.swing.JPanel jPanelEnterprise;
    private javax.swing.JPanel jPanelWorkRequests;
    private javax.swing.JTabbedPane jTabbedSystemAdmin;
    // End of variables declaration//GEN-END:variables
}
