/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildWelfareAdmin;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class ChildWelfareDashboardJPanel extends javax.swing.JPanel {

    private JPanel displayPanel;
    private Entity entity;
    private User user;
    private Enterprise enterprise;

    /**
     * Creates new form ResolveChildWelfareRequestsJPanel
     */
    public ChildWelfareDashboardJPanel(JPanel displayPanel, Entity entity, Enterprise enterprise, User user) {
        initComponents();
        this.displayPanel = displayPanel;
        this.entity = entity;
        this.user = user;
        this.enterprise = enterprise;
        loadGraph();

    }

    private void populateData() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            comboOrganization.addItem(org.getOrganizationName());
        }
    }
    
    private void loadGraph() {
       
       DefaultPieDataset defaultPieDataset = new DefaultPieDataset();
       for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
           defaultPieDataset.setValue(org.getOrganizationName(), org.getWorkQueue().getWorkRequestList().size());
       }
       
       JFreeChart chart = ChartFactory.createPieChart("Pie Chart", defaultPieDataset, true, true, true);
       ChartFrame frame = new ChartFrame("Pie Chart", chart);
       frame.setVisible(true);
       frame.setSize(600,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        comboOrganization = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblOrganizationRequest = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Child Welfare Admin Portal");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 74, 310, 53));

        lblFirstName1.setText("Select Organization:");
        add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 156, 131, 34));

        comboOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrganizationActionPerformed(evt);
            }
        });
        add(comboOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 156, 256, 34));

        tblOrganizationRequest.setBorder(new javax.swing.border.MatteBorder(null));
        tblOrganizationRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        tblOrganizationRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrganizationRequest.setSelectionBackground(new java.awt.Color(117, 177, 169));
        jScrollPane5.setViewportView(tblOrganizationRequest);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 222, 1007, 208));

        btnDetails.setBackground(new java.awt.Color(217, 180, 74));
        btnDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails.setText("Details");
        btnDetails.setContentAreaFilled(false);
        btnDetails.setMaximumSize(new java.awt.Dimension(115, 49));
        btnDetails.setMinimumSize(new java.awt.Dimension(115, 49));
        btnDetails.setOpaque(true);
        btnDetails.setPreferredSize(new java.awt.Dimension(115, 49));
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrganizationActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_comboOrganizationActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrganizationRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Organization selectedOrganization = enterprise.getOrganizationDirectory().getOrganizationList().get(comboOrganization.getSelectedIndex());
        WorkRequest workRequest = (WorkRequest) tblOrganizationRequest.getValueAt(selectedRow, 0);
        ChildWelfareRequestDetails childWelfareDetailsReq = new ChildWelfareRequestDetails(displayPanel, entity, enterprise, user, selectedOrganization, workRequest);
        displayPanel.add(childWelfareDetailsReq);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);
    }//GEN-LAST:event_btnDetailsActionPerformed

    public void populateTable() {
        Organization selectedOrganization = enterprise.getOrganizationDirectory().getOrganizationList().get(comboOrganization.getSelectedIndex());

        DefaultTableModel delModel = (DefaultTableModel) tblOrganizationRequest.getModel();
        delModel.setRowCount(0);
        ArrayList<WorkRequest> workRequestList = selectedOrganization.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : workRequestList) {
            if (workRequest.getReceiver().getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin || workRequest.getSender().getRole().getRoleType() == Role.RoleType.ChildWelfareAdmin ) {

                Object[] row = new Object[2];
                row[0] = workRequest;
                row[1] = workRequest.getStatus();
                delModel.addRow(row);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JComboBox<String> comboOrganization;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrganizationRequest;
    // End of variables declaration//GEN-END:variables

}
