/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ChildWelfareAdmin;

import userinterface.SystemAdminWorkArea.*;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Organizations.Organization;
import Business.Role.Role;
import Business.Users.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class CreateUpdateOrganizationJPanel extends javax.swing.JPanel {

    private JPanel childWelfarePanel;
    private Entity entity;
    private User user;
    private static final int CREATE_OPERATION = 0;
    private static final int UPDATE_OPERATION = 1;
    private int operationId;
    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form CreateUpdateEnterpriseJPanel
     */
    public CreateUpdateOrganizationJPanel(JPanel enterprisePanel, User user, Entity entity, int operationId,Enterprise enterprise, Organization organization) {
        initComponents();
        this.childWelfarePanel = enterprisePanel;
        this.entity = entity;
        this.user = user;
        this.operationId = operationId;
        this.organization = organization;
        this.enterprise = enterprise;
        loadData();
    }

    private void loadData() {
        if (operationId == UPDATE_OPERATION) {
            btnCreate.setText("Update");
            lblTitle.setText("Update Organization");
            txtOrganizationName.setText(organization.getOrganizationName());
            txtOrganizationNo.setText(organization.getOrganizationRegistrationNo());
            txtOrganizationDesc.setText(organization.getOrganizationDesciption());
            txtOrganizationNo.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOrganizationName = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        lblOrganizationDesc = new javax.swing.JLabel();
        txtOrganizationDesc = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblOrganizationNo = new javax.swing.JLabel();
        txtOrganizationNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Organization");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 74, 280, 49));

        lblOrganizationName.setText("Organization Name:");
        add(lblOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 185, 168, 34));

        txtOrganizationName.setSelectionColor(new java.awt.Color(117, 177, 169));
        add(txtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 183, 155, 38));

        lblOrganizationDesc.setText("Organization Description");
        add(lblOrganizationDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 234, 168, 34));

        txtOrganizationDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganizationDescActionPerformed(evt);
            }
        });
        add(txtOrganizationDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 232, 155, 38));

        btnCreate.setBackground(new java.awt.Color(217, 180, 74));
        btnCreate.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.setContentAreaFilled(false);
        btnCreate.setOpaque(true);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 367, 115, 49));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" <<Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 74, 115, 49));

        lblOrganizationNo.setText("Organization Registration No");
        add(lblOrganizationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 283, 168, 34));
        add(txtOrganizationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 281, 155, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        //Validate for emtpy fields
        if (txtOrganizationName.getText().isEmpty() || txtOrganizationDesc.getText().isEmpty() || txtOrganizationNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields ", "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        switch (operationId) {
            case CREATE_OPERATION:
                //validate for registration number
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (org.getOrganizationRegistrationNo().equals(txtOrganizationNo.getText())) {
                        JOptionPane.showMessageDialog(null, "Registration Number Already Exists ", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                enterprise.getOrganizationDirectory().createOrganization(txtOrganizationName.getText(),txtOrganizationDesc.getText(),txtOrganizationNo.getText());
                JOptionPane.showMessageDialog(null, "New Organization Registered", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnBack.doClick();
                break;
            case UPDATE_OPERATION:
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (org.getOrganizationRegistrationNo().equals(organization.getOrganizationRegistrationNo())) {
                        organization.setOrganizationName(txtOrganizationName.getText());
                        organization.setOrganizationDesciption(txtOrganizationDesc.getText());
                        organization.setOrganizationRegistrationNo(txtOrganizationNo.getText());
                    }
                }
                JOptionPane.showMessageDialog(null, "Organization Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnBack.doClick();

                break;
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        childWelfarePanel.remove(this);
        Component[] componentArray = childWelfarePanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChildWelfareOrganizationWorkArea workArea = (ChildWelfareOrganizationWorkArea) component;
        workArea.populateTable();
        CardLayout layout = (CardLayout) childWelfarePanel.getLayout();
        layout.previous(childWelfarePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrganizationDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganizationDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganizationDescActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblOrganizationDesc;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtOrganizationDesc;
    private javax.swing.JTextField txtOrganizationName;
    private javax.swing.JTextField txtOrganizationNo;
    // End of variables declaration//GEN-END:variables
}
