/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalUnit;

import userinterface.PoliceWorkArea.*;
import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Users.User;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.ChildWelfareAdmin.ChildWelfareOrgAdminRolesWorkArea;
import userinterface.ChildWelfareAdmin.ChildWelfareOrganizationWorkArea;
import userinterface.ChildWelfareAdmin.ResolveChildWelfareRequestsJPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class HospitalUnitWorkArea extends javax.swing.JPanel {

    private JPanel displayPanel;
    private Entity entity;
    private User user;
    private Enterprise enterprise;

    /**
     * Creates new form HospitalUnitWorkArea
     */
    public HospitalUnitWorkArea(JPanel displayPanel, Entity entity, Enterprise enterprise, User user) {
        initComponents();
        this.displayPanel = displayPanel;
        this.entity = entity;
        this.user = user;
        this.enterprise = enterprise;
        loadView();
    }

    private void loadView() {
        int selectedIndex = jTabbedHospitalArea.getSelectedIndex();
        if (selectedIndex == 0 || selectedIndex == -1) {
            ChildWelfareHospitalRequestsJPanel workArea = new ChildWelfareHospitalRequestsJPanel(jPanelHomepage, entity, enterprise, user);
            jPanelHomepage.add(workArea);
            CardLayout cardLayout = (CardLayout) jPanelHomepage.getLayout();
            cardLayout.next(jPanelHomepage);
        } 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedHospitalArea = new javax.swing.JTabbedPane();
        jPanelHomepage = new javax.swing.JPanel();

        setBackground(new java.awt.Color(172, 208, 192));

        jTabbedHospitalArea.setBackground(new java.awt.Color(172, 208, 192));

        jPanelHomepage.setBackground(new java.awt.Color(172, 208, 192));
        jPanelHomepage.setLayout(new java.awt.CardLayout());
        jTabbedHospitalArea.addTab("Homepage", new javax.swing.ImageIcon(getClass().getResource("/res/hospital_logo.png")), jPanelHomepage); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedHospitalArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedHospitalArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelHomepage;
    private javax.swing.JTabbedPane jTabbedHospitalArea;
    // End of variables declaration//GEN-END:variables
}
