/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCare;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.FosterCare.FosterCareAttributes;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class FosterCareRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private FosterCareAttributes fosterCareAttributes;

    /**
     * Creates new form FosterCareRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param enterprise
     * @param user
     * @param organization
     */
    public FosterCareRequestForm(JPanel userProcessContainer, Entity entity, Enterprise enterprise,
            User user, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        fosterCareAttributes = new FosterCareAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtChildFullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtChildLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEthnicity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRace = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLegalGuardianName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLegalGuardianMobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLegalGuardianEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLegalGuardianLocation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTemporaryStayExpectedDays = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSubmitRequest = new javax.swing.JButton();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();

        jLabel2.setText("Child Full Name");

        txtChildFullName.setText("jTextField1");

        jLabel1.setText("Child Location");

        txtChildLocation.setText("jTextField1");

        jLabel3.setText("Child Age");

        txtChildAge.setText("jTextField1");

        jLabel4.setText("Child Gender");

        jLabel11.setText("Ethnicity");

        txtEthnicity.setText("jTextField5");

        jLabel12.setText("Race");

        txtRace.setText("jTextField5");

        jLabel10.setText("Remarks");

        txtRemarks.setText("jTextField5");

        jLabel14.setText("Preferred Agency Location");

        txtPreferredAgencyLocation.setText("jTextField5");

        jLabel13.setText("Legal Guardian Name");

        txtLegalGuardianName.setText("jTextField5");

        jLabel15.setText("Legal Guardian Mobile");

        txtLegalGuardianMobile.setText("jTextField5");

        jLabel16.setText("Legal Guardian Email");

        txtLegalGuardianEmail.setText("jTextField5");

        jLabel17.setText("Legal Guardian Location");

        txtLegalGuardianLocation.setText("jTextField5");

        jLabel18.setText("Is Open To Adoption?");

        jLabel19.setText("Expected Duration of Foster Stay");

        txtTemporaryStayExpectedDays.setText("jTextField5");

        buttonGroup1.add(btnYes);
        btnYes.setText("Yes");

        buttonGroup1.add(btnNo);
        btnNo.setText("No");

        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBoy);
        btnBoy.setText("Boy");

        buttonGroup1.add(btnGirl);
        btnGirl.setText("Girl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(txtTemporaryStayExpectedDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(btnYes)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnNo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLegalGuardianMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEthnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreferredAgencyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLegalGuardianEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLegalGuardianLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnSubmitRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnBoy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGirl)))
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGap(95, 95, 95)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChildLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChildFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(381, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoy)
                    .addComponent(btnGirl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEthnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemporaryStayExpectedDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalGuardianLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreferredAgencyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitRequest)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChildFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtChildLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed

        //validations for emtpy fields
        if (txtChildFullName.getText().isEmpty() || (!btnBoy.isEnabled() && !btnGirl.isEnabled()) || txtChildLocation.getText().isEmpty()
                || txtChildAge.getText().isEmpty() || txtEthnicity.getText().isEmpty() || txtRace.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Full Name, Gender, Location, Age, Ethnicity and Race of the child cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (txtLegalGuardianName.getText().isEmpty() || txtLegalGuardianMobile.getText().isEmpty() || 
                txtLegalGuardianEmail.getText().isEmpty() || txtLegalGuardianLocation.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Legal Guardian's name, mobile, email, location cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (txtTemporaryStayExpectedDays.getText().isEmpty() || (!btnYes.isEnabled() && !btnNo.isEnabled()) ) {
            JOptionPane.showMessageDialog(null, "Expected Duration of Foster Stay and Open To Adoption cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean isValid;
        isValid = Validator.getInstance().validateEmailAddr(txtLegalGuardianEmail.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Please enter email address in format - a@b.c", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        isValid = Validator.getInstance().validateAllDigits(txtTemporaryStayExpectedDays.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Please enter expected duration of foster day in days", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        isValid = Validator.getInstance().validateAllDigits(txtChildAge.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Child Age should consist of digits only", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveFosterCareRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(fosterCareAttributes);
        entity.getWorkQueue().addWorkRequest(fosterCareAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildFullName;
    private javax.swing.JTextField txtChildLocation;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtLegalGuardianEmail;
    private javax.swing.JTextField txtLegalGuardianLocation;
    private javax.swing.JTextField txtLegalGuardianMobile;
    private javax.swing.JTextField txtLegalGuardianName;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtRace;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtTemporaryStayExpectedDays;
    // End of variables declaration//GEN-END:variables

    private void saveFosterCareRequestForm() {
        fosterCareAttributes.setChildFullName(txtChildFullName.getText());
        fosterCareAttributes.setChildAge(Integer.parseInt(txtChildAge.getText()));
        fosterCareAttributes.setChildLocation(txtChildLocation.getText());
        fosterCareAttributes.setEthnicity(txtEthnicity.getText());
        fosterCareAttributes.setRace(txtRace.getText());
        fosterCareAttributes.setPreferredAgencyLocation(txtPreferredAgencyLocation.getText());
        fosterCareAttributes.setRemarks(txtRemarks.getText());
        fosterCareAttributes.setLegalGuardianName(txtLegalGuardianName.getText());
        fosterCareAttributes.setLegalGuardianMobile(txtLegalGuardianMobile.getText());
        fosterCareAttributes.setLegalGuardianEmail(txtLegalGuardianEmail.getText());
        fosterCareAttributes.setLegalGuardianLocation(txtLegalGuardianLocation.getText());
        fosterCareAttributes.setTemporaryStayExpectedDays(Integer.parseInt(txtTemporaryStayExpectedDays.getText()));
        
        if(btnBoy.isEnabled()){
            fosterCareAttributes.setChildGender("Male");
        }
        else{
            fosterCareAttributes.setChildGender("Female");
        }

        if (btnYes.isEnabled()) {
            fosterCareAttributes.setOpenToAdoption(true);
        } else {
            fosterCareAttributes.setOpenToAdoption(false);
        }
    }

    private void saveWorkRequest() {
        fosterCareAttributes.setSender(user);
        fosterCareAttributes.setReceiver(organization.getOrganizationAdmin());
        fosterCareAttributes.setRequestDate(LocalDateTime.now());
        fosterCareAttributes.setOrganizationId(organization.getOrganizationId());
        fosterCareAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        fosterCareAttributes.setStatus(Status.StatusType.NEW.getValue());
    }
}
