/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCare;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.FosterCare.FosterCareAttributes;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemUser.SystemUserWorkAreaJPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class FosterCareRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private FosterCareAttributes fosterCareAttributes;

    /**
     * Creates new form FosterCareRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param enterprise
     * @param user
     * @param organization
     */
    public FosterCareRequestForm(JPanel userProcessContainer, Entity entity, Enterprise enterprise,
            User user, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        fosterCareAttributes = new FosterCareAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtChildFullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtChildLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLegalGuardianName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLegalGuardianMobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLegalGuardianEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLegalGuardianLocation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTemporaryStayExpectedDays = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();
        btnSubmitRequest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        comboEthnicity = new javax.swing.JComboBox<>();
        comboRace = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Child Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 105, -1, -1));
        add(txtChildFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 95, 186, 33));

        jLabel1.setText("Child Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 148, -1, -1));
        add(txtChildLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 138, 186, 33));

        jLabel3.setText("Child Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 191, -1, -1));
        add(txtChildAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 181, 186, 33));

        jLabel4.setText("Child Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 224, -1, -1));

        jLabel11.setText("Ethnicity");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 252, -1, 21));

        jLabel12.setText("Race");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 292, -1, 21));

        jLabel10.setText("Remarks");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 546, -1, 21));
        add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 547, 186, -1));

        jLabel14.setText("Preferred Agency Location");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 577, -1, 21));
        add(txtPreferredAgencyLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 578, 186, -1));

        jLabel13.setText("Legal Guardian Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 401, -1, 21));
        add(txtLegalGuardianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 401, 186, 22));

        jLabel15.setText("Legal Guardian Mobile");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 484, -1, 21));
        add(txtLegalGuardianMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 484, 186, 21));

        jLabel16.setText("Legal Guardian Email");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 515, -1, 21));
        add(txtLegalGuardianEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 516, 186, -1));

        jLabel17.setText("Legal Guardian Location");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 441, -1, 21));
        add(txtLegalGuardianLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 441, 186, 25));

        jLabel18.setText("Is Open To Adoption?");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 327, -1, 21));

        jLabel19.setText("Expected Duration of Foster Stay");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 362, -1, 21));
        add(txtTemporaryStayExpectedDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 358, 186, 25));

        btnYes.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnYes);
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 327, -1, -1));

        btnNo.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 327, -1, -1));

        btnBoy.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnBoy);
        btnBoy.setText("Boy");
        add(btnBoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 220, -1, -1));

        btnGirl.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnGirl);
        btnGirl.setText("Girl");
        add(btnGirl, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 220, -1, -1));

        btnSubmitRequest.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setContentAreaFilled(false);
        btnSubmitRequest.setOpaque(true);
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 646, 136, 49));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Foster Care Registration Form");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 21, -1, 49));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 25, 95, 49));

        comboEthnicity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Irish", "Moroccan", "Caucasian", "Nigerian", "Asian Indian", "Chinese", "Korean", " " }));
        add(comboEthnicity, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 247, 186, 30));

        comboRace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "African American", "Native American / Alaskan Native", "Pacific Islander", "Asian", "Native Hawaian", " " }));
        add(comboRace, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 287, 186, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        //validations for emtpy fields
        if (txtChildFullName.getText().isEmpty() || (!btnBoy.isEnabled() && !btnGirl.isEnabled()) || txtChildLocation.getText().isEmpty()
                || txtChildAge.getText().isEmpty() || comboEthnicity.getSelectedItem().toString().isEmpty() || comboRace.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Full Name, Gender, Location, Age, Ethnicity and Race of the child cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtLegalGuardianName.getText().isEmpty() || txtLegalGuardianMobile.getText().isEmpty()
                || txtLegalGuardianEmail.getText().isEmpty() || txtLegalGuardianLocation.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Legal Guardian's name, mobile, email, location cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtTemporaryStayExpectedDays.getText().isEmpty() || (!btnYes.isEnabled() && !btnNo.isEnabled())) {
            JOptionPane.showMessageDialog(null, "Expected Duration of Foster Stay and Open To Adoption cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean isValid;
        isValid = Validator.getInstance().validateEmailAddr(txtLegalGuardianEmail.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Please enter email address in format - a@b.c", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        isValid = Validator.getInstance().validateAllDigits(txtTemporaryStayExpectedDays.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Please enter expected duration of foster day in days", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        isValid = Validator.getInstance().validateAllDigits(txtChildAge.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Child Age should consist of digits only", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveFosterCareRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(fosterCareAttributes);
        entity.getWorkQueue().addWorkRequest(fosterCareAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemUserWorkAreaJPanel workArea = (SystemUserWorkAreaJPanel) component;
        workArea.setVisible(true);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboEthnicity;
    private javax.swing.JComboBox<String> comboRace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildFullName;
    private javax.swing.JTextField txtChildLocation;
    private javax.swing.JTextField txtLegalGuardianEmail;
    private javax.swing.JTextField txtLegalGuardianLocation;
    private javax.swing.JTextField txtLegalGuardianMobile;
    private javax.swing.JTextField txtLegalGuardianName;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtTemporaryStayExpectedDays;
    // End of variables declaration//GEN-END:variables

    private void saveFosterCareRequestForm() {
        fosterCareAttributes.setChildFullName(txtChildFullName.getText());
        fosterCareAttributes.setChildAge(Integer.parseInt(txtChildAge.getText()));
        fosterCareAttributes.setChildLocation(txtChildLocation.getText());
        fosterCareAttributes.setEthnicity(comboEthnicity.getSelectedItem().toString());
        fosterCareAttributes.setRace(comboRace.getSelectedItem().toString());
        fosterCareAttributes.setPreferredAgencyLocation(
                Optional.of(txtPreferredAgencyLocation.getText()).orElse(""));
        fosterCareAttributes.setRemarks(
                Optional.of(txtRemarks.getText()).orElse(""));
        fosterCareAttributes.setLegalGuardianName(txtLegalGuardianName.getText());
        fosterCareAttributes.setLegalGuardianMobile(txtLegalGuardianMobile.getText());
        fosterCareAttributes.setLegalGuardianEmail(txtLegalGuardianEmail.getText());
        fosterCareAttributes.setLegalGuardianLocation(txtLegalGuardianLocation.getText());
        fosterCareAttributes.setTemporaryStayExpectedDays(Integer.parseInt(txtTemporaryStayExpectedDays.getText()));

        if (btnBoy.isEnabled()) {
            fosterCareAttributes.setChildGender("Male");
        } else {
            fosterCareAttributes.setChildGender("Female");
        }

        if (btnYes.isEnabled()) {
            fosterCareAttributes.setOpenToAdoption(true);
        } else {
            fosterCareAttributes.setOpenToAdoption(false);
        }
    }

    private void saveWorkRequest() {
        fosterCareAttributes.setSender(user);
        fosterCareAttributes.setReceiver(organization.getOrganizationAdmin());
        fosterCareAttributes.setRequestDate(LocalDateTime.now());
        fosterCareAttributes.setOrganizationId(organization.getOrganizationId());
        fosterCareAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        fosterCareAttributes.setStatus(Status.StatusType.NEW.getValue());
    }
}
