/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCare;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.FosterCare.FosterCareAttributes;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class FosterCareRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private FosterCareAttributes fosterCareAttributes;

    /**
     * Creates new form FosterCareRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param enterprise
     * @param user
     * @param organization
     */
    public FosterCareRequestForm(JPanel userProcessContainer, Entity entity, Enterprise enterprise,
            User user, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        fosterCareAttributes = new FosterCareAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtChildFullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtChildLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEthnicity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRace = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPreferredAgencyLocation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLegalGuardianName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLegalGuardianMobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLegalGuardianEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLegalGuardianLocation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTemporaryStayExpectedDays = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnBoy = new javax.swing.JRadioButton();
        btnGirl = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnSubmitRequest = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(172, 208, 192));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Child Full Name");

        txtChildFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildFullNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Child Location");

        txtChildLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildLocationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Child Age");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Child Gender");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ethnicity");

        txtEthnicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEthnicityActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Race");

        txtRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRaceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Remarks");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Preferred Agency Location");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Legal Guardian Name");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Legal Guardian Mobile");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Legal Guardian Email");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Legal Guardian Location");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Is Open To Adoption?");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Expected Duration of Foster Stay");

        btnYes.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnYes);
        btnYes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnYes.setText("Yes");

        btnNo.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnNo);
        btnNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnBoy.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnBoy);
        btnBoy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBoy.setText("Boy");

        btnGirl.setBackground(new java.awt.Color(172, 208, 192));
        buttonGroup1.add(btnGirl);
        btnGirl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGirl.setText("Girl");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fostercare Request form");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSubmitRequest.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setContentAreaFilled(false);
        btnSubmitRequest.setOpaque(true);
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        btnBack2.setBackground(new java.awt.Color(217, 180, 74));
        btnBack2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("<< Back");
        btnBack2.setContentAreaFilled(false);
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel2))
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addGap(96, 96, 96)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBoy)
                                .addGap(63, 63, 63)
                                .addComponent(btnGirl))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLegalGuardianEmail)
                                .addComponent(txtPreferredAgencyLocation)
                                .addComponent(txtTemporaryStayExpectedDays, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtLegalGuardianLocation)
                                .addComponent(txtLegalGuardianMobile)
                                .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRemarks)
                                .addComponent(txtRace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEthnicity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnYes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNo)
                                    .addGap(26, 26, 26)))
                            .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChildLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChildFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLegalGuardianEmail, txtLegalGuardianLocation, txtLegalGuardianMobile, txtPreferredAgencyLocation, txtRemarks, txtTemporaryStayExpectedDays});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChildFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChildLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGirl)
                    .addComponent(btnBoy)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEthnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTemporaryStayExpectedDays, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLegalGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLegalGuardianLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLegalGuardianMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLegalGuardianEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreferredAgencyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSubmitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLegalGuardianEmail, txtLegalGuardianLocation, txtLegalGuardianMobile, txtPreferredAgencyLocation, txtRemarks, txtTemporaryStayExpectedDays});

    }// </editor-fold>//GEN-END:initComponents

    private void txtChildFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildFullNameActionPerformed

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        //validations for emtpy fields
        if (txtChildFullName.getText().isEmpty() || (!btnBoy.isEnabled() && !btnGirl.isEnabled()) || txtChildLocation.getText().isEmpty()
                || txtChildAge.getText().isEmpty() || txtEthnicity.getText().isEmpty() || txtRace.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Full Name, Gender, Location, Age, Ethnicity and Race of the child cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (txtLegalGuardianName.getText().isEmpty() || txtLegalGuardianMobile.getText().isEmpty() || 
                txtLegalGuardianEmail.getText().isEmpty() || txtLegalGuardianLocation.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Legal Guardian's name, mobile, email, location cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (txtTemporaryStayExpectedDays.getText().isEmpty() || (!btnYes.isEnabled() && !btnNo.isEnabled()) ) {
            JOptionPane.showMessageDialog(null, "Expected Duration of Foster Stay and Open To Adoption cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean isValid;
        isValid = Validator.getInstance().validateEmailAddr(txtLegalGuardianEmail.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Please enter email address in format - a@b.c", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        isValid = Validator.getInstance().validateAllDigits(txtTemporaryStayExpectedDays.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Please enter expected duration of foster day in days", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        isValid = Validator.getInstance().validateAllDigits(txtChildAge.getText());
        if(!isValid){
            JOptionPane.showMessageDialog(null, "Child Age should consist of digits only", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveFosterCareRequestForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(fosterCareAttributes);
        entity.getWorkQueue().addWorkRequest(fosterCareAttributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);
   
        
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void txtChildLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildLocationActionPerformed

    private void txtEthnicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEthnicityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEthnicityActionPerformed

    private void txtRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRaceActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JRadioButton btnBoy;
    private javax.swing.JRadioButton btnGirl;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildFullName;
    private javax.swing.JTextField txtChildLocation;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtLegalGuardianEmail;
    private javax.swing.JTextField txtLegalGuardianLocation;
    private javax.swing.JTextField txtLegalGuardianMobile;
    private javax.swing.JTextField txtLegalGuardianName;
    private javax.swing.JTextField txtPreferredAgencyLocation;
    private javax.swing.JTextField txtRace;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtTemporaryStayExpectedDays;
    // End of variables declaration//GEN-END:variables

    private void saveFosterCareRequestForm() {
        fosterCareAttributes.setChildFullName(txtChildFullName.getText());
        fosterCareAttributes.setChildAge(Integer.parseInt(txtChildAge.getText()));
        fosterCareAttributes.setChildLocation(txtChildLocation.getText());
        fosterCareAttributes.setEthnicity(txtEthnicity.getText());
        fosterCareAttributes.setRace(txtRace.getText());
        fosterCareAttributes.setPreferredAgencyLocation(txtPreferredAgencyLocation.getText());
        fosterCareAttributes.setRemarks(txtRemarks.getText());
        fosterCareAttributes.setLegalGuardianName(txtLegalGuardianName.getText());
        fosterCareAttributes.setLegalGuardianMobile(txtLegalGuardianMobile.getText());
        fosterCareAttributes.setLegalGuardianEmail(txtLegalGuardianEmail.getText());
        fosterCareAttributes.setLegalGuardianLocation(txtLegalGuardianLocation.getText());
        fosterCareAttributes.setTemporaryStayExpectedDays(Integer.parseInt(txtTemporaryStayExpectedDays.getText()));
        
        if(btnBoy.isEnabled()){
            fosterCareAttributes.setChildGender("Male");
        }
        else{
            fosterCareAttributes.setChildGender("Female");
        }

        if (btnYes.isEnabled()) {
            fosterCareAttributes.setOpenToAdoption(true);
        } else {
            fosterCareAttributes.setOpenToAdoption(false);
        }
    }

    private void saveWorkRequest() {
        fosterCareAttributes.setSender(user);
        fosterCareAttributes.setReceiver(organization.getOrganizationAdmin());
        fosterCareAttributes.setRequestDate(LocalDateTime.now());
        fosterCareAttributes.setOrganizationId(organization.getOrganizationId());
        fosterCareAttributes.setEnterpriseId(enterprise.getEnterpriseId());
        fosterCareAttributes.setStatus(Status.StatusType.NEW.getValue());
    }
}
