/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InternationalOrganizationCollaboration;

import Business.Enterprises.Enterprise;
import Business.Entity;
import Business.Enums.Status;
import Business.InternationalOrganizationCollaboration.InternationalOrganizationCollaborationAttributes;
import Business.Organizations.Organization;
import Business.Users.User;
import Business.Validator.Validator;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemUser.SystemUserWorkAreaJPanel;

/**
 *
 * @author ChildWelfareServicesTeam
 */
public class IntlOrgCollabRequestForm extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Entity entity;
    private Enterprise enterprise;
    private User user;
    private Organization organization;
    private InternationalOrganizationCollaborationAttributes attributes;

    /**
     * Creates new form IntlOrgCollabRequestForm
     *
     * @param userProcessContainer
     * @param entity
     * @param organization
     * @param enterprise
     * @param user
     */
    public IntlOrgCollabRequestForm(JPanel userProcessContainer, Entity entity, Organization organization,
            Enterprise enterprise, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.entity = entity;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        this.attributes = new InternationalOrganizationCollaborationAttributes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtOrgIntlID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrgEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrgCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtOrgCountry = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtOrgType = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRemaks = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPreferredCollabCountry = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(172, 208, 192));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Organization International ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 157, -1, -1));
        add(txtOrgIntlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 154, 166, -1));

        jLabel2.setText("Organization Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 128, -1, -1));
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 125, 166, -1));

        jLabel3.setText("Organization Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 186, -1, -1));
        add(txtOrgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 183, 166, -1));

        jLabel4.setText("Organization City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 215, -1, -1));
        add(txtOrgCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 212, 166, -1));

        jLabel10.setText("Organization Country");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 241, -1, 21));
        add(txtOrgCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 242, 166, -1));

        jLabel11.setText("Organization Type");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 272, -1, 21));
        add(txtOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 273, 166, -1));

        jLabel14.setText("Remarks");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 334, -1, 21));
        add(txtRemaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 335, 166, -1));

        jLabel15.setText("Preferred Collaboration Country");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 303, -1, 21));
        add(txtPreferredCollabCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 304, 166, -1));

        btnSubmitRequest.setBackground(new java.awt.Color(217, 180, 74));
        btnSubmitRequest.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setContentAreaFilled(false);
        btnSubmitRequest.setOpaque(true);
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 407, 220, 50));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Internaltional Organization Collaboration Form");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 44, -1, -1));

        btnBack.setBackground(new java.awt.Color(217, 180, 74));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 48, 91, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        //validations for emtpy fields
        if (txtOrgName.getText().isEmpty() || txtOrgCity.getText().isEmpty()
                || txtOrgCountry.getText().isEmpty() || txtOrgEmail.getText().isEmpty()
                || txtOrgIntlID.getText().isEmpty() || txtOrgType.getText().isEmpty() || txtPreferredCollabCountry.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name, City, Country, Email, Internation ID, Type and Preferred Collaboration Country cannot be empty ",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //validate input
        boolean isValid = Validator.getInstance().validateEmailAddr(txtOrgEmail.getText());
        if (!isValid) {
            JOptionPane.showMessageDialog(null, "Please enter email address in format - a@b.c", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //save form
        saveCollabForm();
        saveWorkRequest();

        //add work request
        organization.getWorkQueue().addWorkRequest(attributes);
        entity.getWorkQueue().addWorkRequest(attributes);
        JOptionPane.showMessageDialog(null, "Your Request Has Been Submitted", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemUserWorkAreaJPanel workArea = (SystemUserWorkAreaJPanel) component;
        workArea.setVisible(true);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtOrgCity;
    private javax.swing.JTextField txtOrgCountry;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgIntlID;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgType;
    private javax.swing.JTextField txtPreferredCollabCountry;
    private javax.swing.JTextField txtRemaks;
    // End of variables declaration//GEN-END:variables

    private void saveCollabForm() {
        attributes.setOrganizationName(txtOrgName.getText());
        attributes.setOrganizationCity(txtOrgCity.getText());
        attributes.setOrganizationInternationalId(txtOrgIntlID.getText());
        attributes.setOrganizationCountry(txtOrgCountry.getText());
        attributes.setOrganizationEmail(txtOrgEmail.getText());
        attributes.setRemarks(Optional.of(txtRemaks.getText()).orElse(""));
        attributes.setOrganizationType(txtOrgType.getText());
        attributes.setPreferredCollaborationCountry(txtPreferredCollabCountry.getText());
    }

    private void saveWorkRequest() {
        attributes.setSender(user);
        attributes.setReceiver(organization.getOrganizationAdmin());
        attributes.setRequestDate(LocalDateTime.now());
        attributes.setOrganizationId(organization.getOrganizationId());
        attributes.setEnterpriseId(enterprise.getEnterpriseId());
        attributes.setStatus(Status.StatusType.NEW.getValue());
    }
}
